# frozen_string_literal: true

namespace :coverage do
  desc "Collate all result sets and push to Coveralls"
  task push: %i[environment collate] do
    require "coveralls"
    Coveralls.push!
  end

  desc "Collate all result sets generated by different test runners"
  task collate: :environment do
    require "simplecov"

    SimpleCov.collate Dir["coverate/.resultset-*.json"], "rails"
  end
end
